apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql_deploy
  labels:
    name: mysql_deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
      name: mysql-pod 
      labels:
        app: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
              #key-value pairs of the secrets
          #secret
        - name: MYSQL_ROOT_PASSWORD
          #secret

        envFrom: 
        - configMapRef:
            # name of the configmap
        volumeMounts:
        - name: mysql-persistent-storage
          mounthPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim: 
          claimName: mysql-pv-claim
        