apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-app-deploy
  labels:
    name: phonebook-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phonebook-app-pod
  template:
    metadata:
      labels:
        app: phonebook-app-pod
    spec:
      containers:
      - name: phonebook-app
        image: serkangumus06/phonebook-main
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          #secret
          valueFrom:
              secretKeyRef:
              #key-value pairs of the secrets
        envFrom:
          - configMapRef:
            # name of the configmap
